# Generated by Django 4.1 on 2023-01-05 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shootingApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="space_shooting",
            options={"managed": False},
        ),
    ]
